timezone: 'CST '
future: false
baseurl: /github-slideshow
highlighter: rouge
markdown: kramdown
lsi: false
permalink: '/:title'
kramdown:
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
plugins:
  - jemoji
title: github-slideshow
author: GitHubTeacher
description: A fun activity for learning Git and GitHub.
sass:
  style: ':compressed'
solarized:
  theme: dark
slideNumber:
  format: c/t
reveal:
  controls: false
  progress: true
  history: true
  keyboard: true
  overview: true
  center: true
  touch: true
  loop: false
  fragments: true
  transition: linear
  backgroundTransition: slide
  width: 1000
  height: 920
  margin: 0.1
  minScale: 0.2
  maxScale: 1.5
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - reveal.js/test
  - reveal.js/index.html
  - reveal.js/README.md
  - reveal.js/bower.json
  - reveal.js/Gruntfile.js
  - reveal.js/CONTRIBUTING.md
  - reveal.js/LICENSE
  - reveal.js/package.json
